batch_size: 256
total_timestep: 5000000
gamma: 0.995
learning_rate: 5e-05
num_envs: 10
ppo_clip_range: 0.2
ppo_ent_coef: 0.0
ppo_gae_lambda: 0.95
ppo_max_grad_norm: 0.5
ppo_n_epochs: 10
rollout_n_steps: 256
save_step_log: true
eval_freq: 100
eval_episode_count: 30
wandb_in_model: False
wandb_in_env: False
wandb_project_name: "test_prj"
wandb_graph_name: "run"